version: "3.9"
services:
  build:
    build: .
    # see https://github.com/compose-spec/compose-spec/issues/94
    user: ${CURRENT_UID}
    working_dir: /code
    environment:
      - PS2HOSTNAME=192.168.1.10
    command: ["make", "all"]
    volumes:
      - ${PWD}:/code
