version: "3.9"
services:
  repo:
    # this allows to not invoke `docker build . -t helloworld`
    image: ${APP_NAME}
    build: .
    #  context: .
    working_dir: ${PS2_WORKSPACE}
    command: >
      sh -c "repo init -q --no-clone-bundle -u ${MANIFEST_URL} -b ${MANIFEST_BRANCH} &&
             repo sync -j8 ${APP_NAME}.git"
    volumes:
      - ${PS2_WORKSPACE}:${PS2_WORKSPACE}

  make:
    image: ${APP_NAME}
    depends_on:
      - repo
    # see https://github.com/compose-spec/compose-spec/issues/94
    # user: ${CURRENT_UID}
    working_dir: ${PS2_WORKSPACE}/apps/${APP_NAME}
    command: make ${MAKE_ARGS}
    volumes:
      - ${PS2_WORKSPACE}:${PS2_WORKSPACE}

#TODO ; it would make sense to add your project to repo manifest and checkout with repo.
# avoid to use github actions/checkout
