version: "3.9"
services:
  checkout:
    # this allows to not invoke `docker build . -t helloworld`
    build: .
    image: ${APP_NAME}
    working_dir: /workspace
    command: >
      sh -c "RUN repo init -q -u https://github.com/bignaux/ps2pkgs.git &&
             repo init -m apps/${APP_NAME}/helloworld_local_manifest.xml &&
             repo sync --fail-fast"
    volumes:
      - workspace:/workspace

  build:
    image: ${APP_NAME}
    depends_on:
      - checkout
    # see https://github.com/compose-spec/compose-spec/issues/94
    # user: ${CURRENT_UID}
    working_dir: /workspace/apps/${APP_NAME}
    command: make ${MAKE_ARGS}
    volumes:
      - workspace:/workspace

#TODO ; it would make sense to add your project to repo manifest and checkout with repo.
# avoid to use github actions/checkout

volumes:
  workspace:
