version: "3.9"
services:
  make:
    # this allows to not invoke `docker build .``
    build:
      context: .
    container_name: helloworld
    # see https://github.com/compose-spec/compose-spec/issues/94
    user: ${CURRENT_UID}
    working_dir: /app
    environment:
      - PS2HOSTNAME=192.168.1.10
      - makeargs
    command: make $makeargs
    volumes:
      - ${PWD}:/app
