version: "3.9"
services:
  repo:
    # this allows to not invoke `docker build . -t helloworld`
    build:
      context: .
    container_name: helloworld
    working_dir: /workspace
    command: repo init -q --no-clone-bundle -u ${manifest_url} -b ${manifest_branch}
    volumes:
      - ${PS2_WORKSPACE}:/workspace

  make:
    image: helloworld_repo
    depends_on:
      - repo
    # see https://github.com/compose-spec/compose-spec/issues/94
    # user: ${CURRENT_UID}
    working_dir: /app
    command: make ${MAKE_ARGS}
    volumes:
      - ${PWD}:/app
