name: Issue report
description: Create a report to help us improve
title: "[ISSUE]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### __Disclaimer:__
        Before posting the issue confirm that you meet the below requirements.

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: "Check before posting"
      options:
        - label: I have checked existing issues for duplicates and found none

  - type: textarea
    id: explanation
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: My issue is...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Configuration
        > (please complete the following information):

  - type: input
    id: console
    attributes:
      label: Console model
      description: you can see it on the console sticker or inside OSDSYS (press triangle on main menú)
      placeholder: SCPH-?????
    validations:
      required: true

