name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: 'apps/helloworld'

    - name: PS2_WORKSPACE Checkout
      run: docker compose up checkout

    - name: Run clang-format Linter
      #continue-on-error: true
      run: MAKE_ARGS=check docker compose up build

    - name: Compile project
      run: docker compose up build
    # commands for compiling your project

    # - name: Prepare artifacts
        # zip *.elf
        # create realease archive
    - name: Get short SHA and repository name
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}
        path: |
          *.elf
    # 'path' will create artifact with all *.elf in working directory
    # you can change this

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest development build"
        files: |
          *.elf
    # 'files' will create release with all *.elf in working directory
    # you can change this
